version: "3.8"
services:
  frontend:
    build: 
      context: ./frontend
    volumes:
      - "./frontend:/usr/src/app"
    network_mode: host
  backend:
    build: 
      context: ./backend
    volumes:
      - "./backend:/usr/src/app"
    network_mode: host
